[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = 'VimEnter'
hook_post_source = '''
  lua require('plugins.lspconfig')
'''

[[plugins]]
repo = 'glepnir/lspsaga.nvim'
on_event = 'VimEnter'
on_source = 'nvim-lspconfig'
hook_post_source = '''
  lua require('plugins.lspsaga')
'''

[[plugins]]
repo = 'hrsh7th/nvim-cmp'
on_event = 'VimEnter'
on_source = 'nvim-lspconfig'
hook_source = '''
  lua require('plugins.nvim-cmp')
'''

[[plugins]]
on_source = 'nvim-cmp'
repo = 'hrsh7th/cmp-nvim-lsp'

[[plugins]]
on_source = 'nvim-cmp'
repo = 'hrsh7th/cmp-path'

[[plugins]]
on_source = 'nvim-cmp'
repo = 'hrsh7th/cmp-buffer'

[[plugins]]
repo = 'saadparwaiz1/cmp_luasnip'
on_source = 'nvim-cmp'
hook_source = '''
  lua require('plugins.cmp_luasnip')
'''

[[plugins]]
on_source = 'nvim-cmp'
repo = 'L3MON4D3/LuaSnip'
