[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = 'VimEnter'
hook_post_source = '''
  lua require('plugins.lspconfig')
'''


[[plugins]]
repo = 'hrsh7th/nvim-cmp'
on_event = 'VimEnter'
on_source = 'nvim-lspconfig'
hook_source = '''
  lua require('plugins.nvim-cmp')
'''

[[plugins]]
on_source = 'nvim-cmp'
repo = 'hrsh7th/cmp-nvim-lsp'

[[plugins]]
on_source = 'nvim-cmp'
repo = 'hrsh7th/cmp-path'

[[plugins]]
on_source = 'nvim-cmp'
repo = 'hrsh7th/cmp-buffer'
