[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'glepnir/zephyr-nvim'
hook_source = '''
  colorscheme zephyr
'''

[[plugins]]
repo = 'Akin909/nvim-bufferline.lua'
hook_source = '''
  lua require('plugins.bufferline')
'''

[[plugins]]
repo = 'glepnir/galaxyline.nvim'
hook_source = '''
  lua require('plugins.eviline')
'''

[[plugins]]
repo = 'glepnir/dashboard-nvim'
hook_source = '''
  lua require('plugins.dashboard')
'''

[[plugins]]
repo = 'edluffy/hologram.nvim'
if = 0
hook_source = '''
  lua require('plugins.hologram')
'''
