[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'glepnir/zephyr-nvim'
hook_source = '''
  colorscheme zephyr
'''

[[plugins]]
repo = 'Akin909/nvim-bufferline.lua'
hook_source = '''
  lua require('plugins.bufferline')
'''

[[plugins]]
repo = 'glepnir/galaxyline.nvim'
hook_source = '''
  lua require('plugins.eviline')
'''

# [[plugins]]
# repo = 'nvimdev/dashboard-nvim'
# hook_source = '''
#   lua require('plugins.dashboard')
# '''
