[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

# for wilder
[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
  " use hook_add, otherwise it will disable after restart
  let g:onedark_hide_endofbuffer = 1
'''
hook_post_source = '''
  let g:onedark_color_overrides = {
  \ "special_grey": { "gui": "#818387", "cterm": "170", "cterm16": "5" },
  \ "comment_grey": { "gui": "#8b8d91", "cterm": "170", "cterm16": "5" }
  \}
  " grey = { '#5c6370', '#535965' , '#546178' , '#455574' , '#646568' , '#5a5b5e' },
  " light_grey = { '#848b98', '#7a818e' , '#7d899f' , '#6c7d9c' , '#8b8d91' , '#818387' },
  colorscheme onedark
'''

[[plugins]]
repo = 'Akin909/nvim-bufferline.lua'
hook_post_source = '''
  lua require('plugins.bufferline')
'''

[[plugins]]
repo = 'glepnir/galaxyline.nvim'
hook_post_source = '''
  lua require('plugins.eviline')
'''

[[plugins]]
repo = 'glepnir/dashboard-nvim'
hook_add = '''
  let g:dashboard_preview_command = 'cat'
  let g:dashboard_preview_pipeline = 'lolcat'
  let g:dashboard_preview_file = getenv('HOME') . '/.config/nvim/static/neovim.cat'
  let g:dashboard_preview_file_height = 10
  let g:dashboard_preview_file_width = 80
  let g:dashboard_default_executive ='telescope'
  let g:dashboard_custom_section = {
    \ 'last_session'        :{
        \ 'description': ['  Recently laset session                  SPC s l'],
        \ 'command': 'SessionLoad'},
    \ 'find_history'        :{
        \ 'description': ['  Recently opened files                   SPC c h'],
        \ 'command': 'DashboardFindHistory'},
    \ 'find_file'           :{
        \ 'description': ['  Find  File                              SPC c f'],
        \ 'command': 'DashboardFindFile'},
    \ 'new_file'            :{
        \ 'description': ['  New   File                              SPC d n'],
        \ 'command': 'DashboardNewFile'},
    \ 'find_word'           :{
        \ 'description': ['  Find  word                              SPC c a'],
        \ 'command': 'DashboardFindWord'},
    \}
'''

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'