[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
on_event = 'BufReadPre'
hook_source = '''
  lua require ('plugins.indent-blankline')
'''

[[plugins]]
repo = 'rhysd/accelerated-jk'
on_map = {n = '<Plug>'}
hook_add = '''
  nmap j <Plug>(accelerated_jk_gj)
  nmap k <Plug>(accelerated_jk_gk)
'''

[[plugins]]
repo = 'kyazdani42/nvim-tree.lua'
on_cmd = ['NvimTreeToggle', 'NvimTreeOpen', 'NvimTreeFindFile']
# on_event = 'VimEnter'
hook_source = '''
  lua require ('plugins.nvim-tree')
'''

[[plugins]]
repo = 'nvim-telescope/telescope-fzy-native.nvim'
on_source = 'telescope.nvim'

[[plugins]]
repo = 'nvim-lua/popup.nvim'
on_source = 'telescope.nvim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
on_source = 'telescope.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
on_lua = 'telescope'
hook_source = '''
lua require('plugins.telescope')
'''

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
on_event = 'BufReadPre'
depends = 'plenary.nvim'
hook_source = '''
lua require('plugins.gitsigns')
'''

[[plugins]]
repo = 'sindrets/diffview.nvim'
on_cmd = ['DiffviewOpen', 'DiffviewFileHistory']

[[plugins]]
repo = 'TimUntersberger/neogit'
on_cmd = 'Neogit'
depends = ['plenary.nvim', 'diffview.nvim']
hook_source = '''
  lua require('plugins.neogit')
'''

[[plugins]]
repo = 'kana/vim-niceblock'
on_map = {x = '<Plug>'}
hook_add = '''
  xmap I  <Plug>(niceblock-I)
  xmap gI <Plug>(niceblock-gI)
  xmap A  <Plug>(niceblock-A)
'''

[[plugins]]
repo = 'liuchengxu/vista.vim'
on_cmd = 'Vista'
hook_source = '''
  let g:vista#renderer#enable_icon = 1
  let g:vista_disable_statusline = 1
  let g:vista_default_executive = 'coc'
  " let g:vista_default_executive = 'ctags'
  let g:vista_echo_cursor_strategy = 'floating_win'
  let g:vista_vimwiki_executive = 'markdown'
  let g:vista_executive_for = {
    \ 'markdown': 'toc',
    \ 'tex': 'coc',
    \ 'python': 'coc',
    \ 'vim': 'coc',
    \ 'cpp': 'coc',
    \ 'cu': 'coc',
    \ 'cc': 'coc',
    \ }
  let g:vista#renderer#icons = {
              \   "function": "\uf794",
              \   "variable": "\u0ec2",
              \   "label": "笠", 
              \   "subsection": "", 
              \   "section": "", 
              \   "paragraph": "", 
              \   "subsubsection": "",
              \  }
'''

[[plugins]]
repo = 'akinsho/nvim-toggleterm.lua'
on_cmd = ['ToggleTerm', 'TermExec']
hook_source = '''
lua require('plugins.toogleterm')
'''
