require("indent_blankline").setup({
  enabled = true,
  -- char = "|",
  char = "│",
  -- char_list = {"", "┊", "┆", "¦", "|", "¦", "┆", "┊", ""},
  filetype_exclude = { "help", "startify", "dashboard", "packer", "guihua", "NvimTree", "sidekick" },
  show_trailing_blankline_indent = false,
  show_first_indent_level = true,
  buftype_exclude = { "terminal" },
  space_char_blankline = " ",
  use_treesitter = true,
  show_current_context = false,
  context_patterns = {
    "class",
    "return",
    "function",
    "method",
    "^if",
    "if",
    "^while",
    "jsx_element",
    "^for",
    "for",
    "^object",
    "^table",
    "block",
    "arguments",
    "if_statement",
    "else_clause",
    "jsx_element",
    "jsx_self_closing_element",
    "try_statement",
    "catch_clause",
    "import_statement",
    "operation_type",
  },
  -- bufname_exclude = {"README.md"}
})
